main: raise error if imager source is missing
Using the test config:

    Traceback (most recent call last):
      File "main_gui/main.py", line 192, in __init__
	raise AttributeError("config has no imager source")
    AttributeError: config has no imager source

Signed-off-by: Filipe Laíns <lains@archlinux.org>