main: fix destructor when cnc_thread is not set
If we fail before cnc_thread is set, we would try to stop it and result
in the following error.

    Exception ignored in: <function MainWindow.__del__ at 0x7fe811086dc0>
    Traceback (most recent call last):
      File "main_gui/main.py", line 250, in __del__
	self.shutdown()
      File "main_gui/main.py", line 253, in shutdown
	self.cnc_thread.hal.ar_stop()
    AttributeError: 'MainWindow' object has no attribute 'cnc_thread'

Signed-off-by: Filipe Laíns <lains@archlinux.org>